#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AnylineXamarinApp.Resource", IsApplication=true)]

namespace AnylineXamarinApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f060001
			public const int example_activity_classes = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int example_activity_names = 2131099648;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f01002c
			public const int api_2_enabled = 2130772012;
			
			// aapt resource value: 0x7f010006
			public const int beep_on_result = 2130771974;
			
			// aapt resource value: 0x7f010008
			public const int blink_animation_on_result = 2130771976;
			
			// aapt resource value: 0x7f01002b
			public const int camera_id = 2130772011;
			
			// aapt resource value: 0x7f010009
			public const int cancel_on_result = 2130771977;
			
			// aapt resource value: 0x7f010013
			public const int cutout_alignment = 2130771987;
			
			// aapt resource value: 0x7f010022
			public const int cutout_crop_offset_x = 2130772002;
			
			// aapt resource value: 0x7f010023
			public const int cutout_crop_offset_y = 2130772003;
			
			// aapt resource value: 0x7f010020
			public const int cutout_crop_padding_x = 2130772000;
			
			// aapt resource value: 0x7f010021
			public const int cutout_crop_padding_y = 2130772001;
			
			// aapt resource value: 0x7f01001f
			public const int cutout_drawable = 2130771999;
			
			// aapt resource value: 0x7f01000a
			public const int cutout_feedback_stroke_color = 2130771978;
			
			// aapt resource value: 0x7f010016
			public const int cutout_max_height_percent = 2130771990;
			
			// aapt resource value: 0x7f010015
			public const int cutout_max_width_percent = 2130771989;
			
			// aapt resource value: 0x7f010017
			public const int cutout_offset_x = 2130771991;
			
			// aapt resource value: 0x7f010018
			public const int cutout_offset_y = 2130771992;
			
			// aapt resource value: 0x7f010024
			public const int cutout_outside_color = 2130772004;
			
			// aapt resource value: 0x7f01001d
			public const int cutout_ratio_from_size_height = 2130771997;
			
			// aapt resource value: 0x7f01001c
			public const int cutout_ratio_from_size_width = 2130771996;
			
			// aapt resource value: 0x7f01001e
			public const int cutout_rect_corner_radius_in_dp = 2130771998;
			
			// aapt resource value: 0x7f01001b
			public const int cutout_stroke_color = 2130771995;
			
			// aapt resource value: 0x7f01001a
			public const int cutout_stroke_width_in_dp = 2130771994;
			
			// aapt resource value: 0x7f010019
			public const int cutout_style = 2130771993;
			
			// aapt resource value: 0x7f010014
			public const int cutout_width = 2130771988;
			
			// aapt resource value: 0x7f010026
			public const int flash_alignment = 2130772006;
			
			// aapt resource value: 0x7f010029
			public const int flash_image_auto = 2130772009;
			
			// aapt resource value: 0x7f010028
			public const int flash_image_off = 2130772008;
			
			// aapt resource value: 0x7f010027
			public const int flash_image_on = 2130772007;
			
			// aapt resource value: 0x7f010025
			public const int flash_mode = 2130772005;
			
			// aapt resource value: 0x7f010000
			public const int overlay_drawable = 2130771968;
			
			// aapt resource value: 0x7f010001
			public const int overlay_outside_color = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int preferred_picture_height = 2130771970;
			
			// aapt resource value: 0x7f010003
			public const int preferred_picture_width = 2130771971;
			
			// aapt resource value: 0x7f010004
			public const int preferred_preview_height = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int preferred_preview_width = 2130771973;
			
			// aapt resource value: 0x7f01002a
			public const int show_fps = 2130772010;
			
			// aapt resource value: 0x7f010007
			public const int vibrate_on_result = 2130771975;
			
			// aapt resource value: 0x7f010011
			public const int visual_feedback_animation_duration = 2130771985;
			
			// aapt resource value: 0x7f010010
			public const int visual_feedback_animation_style = 2130771984;
			
			// aapt resource value: 0x7f01000f
			public const int visual_feedback_corner_radius_in_dp = 2130771983;
			
			// aapt resource value: 0x7f01000e
			public const int visual_feedback_fill_color = 2130771982;
			
			// aapt resource value: 0x7f010012
			public const int visual_feedback_redraw_timeout = 2130771986;
			
			// aapt resource value: 0x7f01000c
			public const int visual_feedback_stroke_color = 2130771980;
			
			// aapt resource value: 0x7f01000d
			public const int visual_feedback_stroke_width_in_dp = 2130771981;
			
			// aapt resource value: 0x7f01000b
			public const int visual_feedback_style = 2130771979;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int bottle_background = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int flash_control_background = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int flash_icon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int flash_icon_auto = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int flash_icon_off = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int gift_card_background = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int iban_background = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ic_barcode = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ic_card = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int ic_energy = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int ic_energy_old = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int ic_launcher = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int ic_mrz = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int license_plate_background = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int passport_background = 2130837518;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080018
			public const int any = 2131230744;
			
			// aapt resource value: 0x7f080011
			public const int auto = 2131230737;
			
			// aapt resource value: 0x7f080019
			public const int back = 2131230745;
			
			// aapt resource value: 0x7f080028
			public const int barcode_result_text = 2131230760;
			
			// aapt resource value: 0x7f08001b
			public const int barcode_scan_view = 2131230747;
			
			// aapt resource value: 0x7f080004
			public const int blink = 2131230724;
			
			// aapt resource value: 0x7f08000b
			public const int bottom = 2131230731;
			
			// aapt resource value: 0x7f08000c
			public const int bottom_half = 2131230732;
			
			// aapt resource value: 0x7f080014
			public const int bottom_left = 2131230740;
			
			// aapt resource value: 0x7f080015
			public const int bottom_right = 2131230741;
			
			// aapt resource value: 0x7f08000d
			public const int center = 2131230733;
			
			// aapt resource value: 0x7f080000
			public const int contour_point = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int contour_rect = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int contour_underline = 2131230722;
			
			// aapt resource value: 0x7f08001e
			public const int document_scan_view = 2131230750;
			
			// aapt resource value: 0x7f080022
			public const int energy_scan_view = 2131230754;
			
			// aapt resource value: 0x7f08001a
			public const int front = 2131230746;
			
			// aapt resource value: 0x7f080020
			public const int full_image = 2131230752;
			
			// aapt resource value: 0x7f080010
			public const int image = 2131230736;
			
			// aapt resource value: 0x7f08001f
			public const int image_result = 2131230751;
			
			// aapt resource value: 0x7f080005
			public const int kitt = 2131230725;
			
			// aapt resource value: 0x7f080029
			public const int listView = 2131230761;
			
			// aapt resource value: 0x7f080035
			public const int main_layout = 2131230773;
			
			// aapt resource value: 0x7f080012
			public const int manual = 2131230738;
			
			// aapt resource value: 0x7f08002b
			public const int mrz_result = 2131230763;
			
			// aapt resource value: 0x7f08002a
			public const int mrz_scan_view = 2131230762;
			
			// aapt resource value: 0x7f080013
			public const int none = 2131230739;
			
			// aapt resource value: 0x7f080036
			public const int ocr_scan_view = 2131230774;
			
			// aapt resource value: 0x7f080006
			public const int pulse = 2131230726;
			
			// aapt resource value: 0x7f080007
			public const int pulse_random = 2131230727;
			
			// aapt resource value: 0x7f080023
			public const int radio_button_header = 2131230755;
			
			// aapt resource value: 0x7f080024
			public const int radio_group = 2131230756;
			
			// aapt resource value: 0x7f080003
			public const int rect = 2131230723;
			
			// aapt resource value: 0x7f080008
			public const int resize = 2131230728;
			
			// aapt resource value: 0x7f080037
			public const int result_background = 2131230775;
			
			// aapt resource value: 0x7f080021
			public const int root = 2131230753;
			
			// aapt resource value: 0x7f08001d
			public const int text = 2131230749;
			
			// aapt resource value: 0x7f08002d
			public const int text_country_code_national = 2131230765;
			
			// aapt resource value: 0x7f080031
			public const int text_day_of_birth = 2131230769;
			
			// aapt resource value: 0x7f080032
			public const int text_expiration_date = 2131230770;
			
			// aapt resource value: 0x7f080030
			public const int text_given_names = 2131230768;
			
			// aapt resource value: 0x7f080034
			public const int text_mrz = 2131230772;
			
			// aapt resource value: 0x7f08002e
			public const int text_number = 2131230766;
			
			// aapt resource value: 0x7f08001c
			public const int text_result = 2131230748;
			
			// aapt resource value: 0x7f080033
			public const int text_sex = 2131230771;
			
			// aapt resource value: 0x7f08002f
			public const int text_surnames = 2131230767;
			
			// aapt resource value: 0x7f08002c
			public const int text_type = 2131230764;
			
			// aapt resource value: 0x7f080025
			public const int toggle_barcode_layout = 2131230757;
			
			// aapt resource value: 0x7f080027
			public const int toggle_barcode_switch = 2131230759;
			
			// aapt resource value: 0x7f080026
			public const int toggle_barcode_text = 2131230758;
			
			// aapt resource value: 0x7f08000e
			public const int top = 2131230734;
			
			// aapt resource value: 0x7f08000f
			public const int top_half = 2131230735;
			
			// aapt resource value: 0x7f080016
			public const int top_left = 2131230742;
			
			// aapt resource value: 0x7f080017
			public const int top_right = 2131230743;
			
			// aapt resource value: 0x7f080009
			public const int traverse_multi = 2131230729;
			
			// aapt resource value: 0x7f08000a
			public const int traverse_single = 2131230730;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int BarcodeActivity = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int DialogResult = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int DocumentActivity = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int EnergyActivity = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int MainActivity = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int MrzActivity = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int MrzResult = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int OCRActivity = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int OCRResult = 2130903048;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f040000
			public const int al_d6f3e042d13f4cc06b77dbdb2d2dcebaf46326e6 = 2130968576;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050007
			public const int ApplicationName = 2131034119;
			
			// aapt resource value: 0x7f050000
			public const int allow_camera_permission = 2131034112;
			
			// aapt resource value: 0x7f05001b
			public const int category_barcodes = 2131034139;
			
			// aapt resource value: 0x7f05001c
			public const int category_documents = 2131034140;
			
			// aapt resource value: 0x7f050018
			public const int category_energy = 2131034136;
			
			// aapt resource value: 0x7f05001a
			public const int category_fintech = 2131034138;
			
			// aapt resource value: 0x7f050019
			public const int category_identification = 2131034137;
			
			// aapt resource value: 0x7f05001d
			public const int category_loyality = 2131034141;
			
			// aapt resource value: 0x7f05001e
			public const int category_vehicle = 2131034142;
			
			// aapt resource value: 0x7f050001
			public const int contact_info = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int flash_auto = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int flash_off = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int flash_on = 2131034116;
			
			// aapt resource value: 0x7f050015
			public const int heat_meter_4_3 = 2131034133;
			
			// aapt resource value: 0x7f050016
			public const int heat_meter_5_3 = 2131034134;
			
			// aapt resource value: 0x7f050017
			public const int heat_meter_6_3 = 2131034135;
			
			// aapt resource value: 0x7f050005
			public const int license_expiry_info = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int open_permission_settings = 2131034118;
			
			// aapt resource value: 0x7f05000b
			public const int scan_analog_digital_meter = 2131034123;
			
			// aapt resource value: 0x7f050008
			public const int scan_analog_meter = 2131034120;
			
			// aapt resource value: 0x7f05000c
			public const int scan_barcode = 2131034124;
			
			// aapt resource value: 0x7f050011
			public const int scan_bottlecaps = 2131034129;
			
			// aapt resource value: 0x7f050009
			public const int scan_digital_meter = 2131034121;
			
			// aapt resource value: 0x7f05000e
			public const int scan_document = 2131034126;
			
			// aapt resource value: 0x7f05000a
			public const int scan_heat_meter = 2131034122;
			
			// aapt resource value: 0x7f050010
			public const int scan_iban = 2131034128;
			
			// aapt resource value: 0x7f050012
			public const int scan_license_plates = 2131034130;
			
			// aapt resource value: 0x7f050013
			public const int scan_license_plates_austria = 2131034131;
			
			// aapt resource value: 0x7f050014
			public const int scan_license_plates_germany = 2131034132;
			
			// aapt resource value: 0x7f05000d
			public const int scan_mrz = 2131034125;
			
			// aapt resource value: 0x7f05000f
			public const int scan_voucher_code = 2131034127;
			
			// aapt resource value: 0x7f05001f
			public const int version_info = 2131034143;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int AppTheme = 2131165184;
			
			// aapt resource value: 0x7f070002
			public const int MrzResultMrzText = 2131165186;
			
			// aapt resource value: 0x7f070001
			public const int MrzResultText = 2131165185;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] AnylineBaseModuleView = new int[] {
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984,
					2130771985,
					2130771986};
			
			// aapt resource value: 0
			public const int AnylineBaseModuleView_beep_on_result = 0;
			
			// aapt resource value: 2
			public const int AnylineBaseModuleView_blink_animation_on_result = 2;
			
			// aapt resource value: 3
			public const int AnylineBaseModuleView_cancel_on_result = 3;
			
			// aapt resource value: 4
			public const int AnylineBaseModuleView_cutout_feedback_stroke_color = 4;
			
			// aapt resource value: 1
			public const int AnylineBaseModuleView_vibrate_on_result = 1;
			
			// aapt resource value: 11
			public const int AnylineBaseModuleView_visual_feedback_animation_duration = 11;
			
			// aapt resource value: 10
			public const int AnylineBaseModuleView_visual_feedback_animation_style = 10;
			
			// aapt resource value: 9
			public const int AnylineBaseModuleView_visual_feedback_corner_radius_in_dp = 9;
			
			// aapt resource value: 8
			public const int AnylineBaseModuleView_visual_feedback_fill_color = 8;
			
			// aapt resource value: 12
			public const int AnylineBaseModuleView_visual_feedback_redraw_timeout = 12;
			
			// aapt resource value: 6
			public const int AnylineBaseModuleView_visual_feedback_stroke_color = 6;
			
			// aapt resource value: 7
			public const int AnylineBaseModuleView_visual_feedback_stroke_width_in_dp = 7;
			
			// aapt resource value: 5
			public const int AnylineBaseModuleView_visual_feedback_style = 5;
			
			public static int[] AnylineView = new int[] {
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771987,
					2130771988,
					2130771989,
					2130771990,
					2130771991,
					2130771992,
					2130771993,
					2130771994,
					2130771995,
					2130771996,
					2130771997,
					2130771998,
					2130771999,
					2130772000,
					2130772001,
					2130772002,
					2130772003,
					2130772004,
					2130772005,
					2130772006,
					2130772007,
					2130772008,
					2130772009};
			
			// aapt resource value: 4
			public const int AnylineView_cutout_alignment = 4;
			
			// aapt resource value: 19
			public const int AnylineView_cutout_crop_offset_x = 19;
			
			// aapt resource value: 20
			public const int AnylineView_cutout_crop_offset_y = 20;
			
			// aapt resource value: 17
			public const int AnylineView_cutout_crop_padding_x = 17;
			
			// aapt resource value: 18
			public const int AnylineView_cutout_crop_padding_y = 18;
			
			// aapt resource value: 16
			public const int AnylineView_cutout_drawable = 16;
			
			// aapt resource value: 7
			public const int AnylineView_cutout_max_height_percent = 7;
			
			// aapt resource value: 6
			public const int AnylineView_cutout_max_width_percent = 6;
			
			// aapt resource value: 8
			public const int AnylineView_cutout_offset_x = 8;
			
			// aapt resource value: 9
			public const int AnylineView_cutout_offset_y = 9;
			
			// aapt resource value: 21
			public const int AnylineView_cutout_outside_color = 21;
			
			// aapt resource value: 14
			public const int AnylineView_cutout_ratio_from_size_height = 14;
			
			// aapt resource value: 13
			public const int AnylineView_cutout_ratio_from_size_width = 13;
			
			// aapt resource value: 15
			public const int AnylineView_cutout_rect_corner_radius_in_dp = 15;
			
			// aapt resource value: 12
			public const int AnylineView_cutout_stroke_color = 12;
			
			// aapt resource value: 11
			public const int AnylineView_cutout_stroke_width_in_dp = 11;
			
			// aapt resource value: 10
			public const int AnylineView_cutout_style = 10;
			
			// aapt resource value: 5
			public const int AnylineView_cutout_width = 5;
			
			// aapt resource value: 23
			public const int AnylineView_flash_alignment = 23;
			
			// aapt resource value: 26
			public const int AnylineView_flash_image_auto = 26;
			
			// aapt resource value: 25
			public const int AnylineView_flash_image_off = 25;
			
			// aapt resource value: 24
			public const int AnylineView_flash_image_on = 24;
			
			// aapt resource value: 22
			public const int AnylineView_flash_mode = 22;
			
			// aapt resource value: 0
			public const int AnylineView_preferred_picture_height = 0;
			
			// aapt resource value: 1
			public const int AnylineView_preferred_picture_width = 1;
			
			// aapt resource value: 2
			public const int AnylineView_preferred_preview_height = 2;
			
			// aapt resource value: 3
			public const int AnylineView_preferred_preview_width = 3;
			
			public static int[] CameraBridgeViewBase = new int[] {
					2130772010,
					2130772011};
			
			// aapt resource value: 1
			public const int CameraBridgeViewBase_camera_id = 1;
			
			// aapt resource value: 0
			public const int CameraBridgeViewBase_show_fps = 0;
			
			public static int[] CameraView = new int[] {
					2130772012};
			
			// aapt resource value: 0
			public const int CameraView_api_2_enabled = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
